# Generated by Django 5.0.7 on 2024-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('output', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ifconfig',
        ),
        migrations.DeleteModel(
            name='Touchfile',
        ),
    ]
