# Generated by Django 5.0.7 on 2024-08-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_commandsresult_delete_ifconfig_delete_touchfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
    ]
